### ISSUE TITLE
samtoolsのエラーについて2

### ISSUE THREAD

**Issue by ni6o6** [nig-sc/nigsc_homepage2#447]
先に同じような質問があったのですが、少し異なるので新しく質問させてください。
Discussed in https://github.com/nig-sc/nigsc_homepage2/discussions/422

OSの変更後、自分のdirにインストールしていたsamtoolsが認識されなくなりました。
"error while loading shared libraries: libcrypto.so.10: cannot open shared object file: No such file or directory"

もう一度インストールし直すかと思い、
```
tar xjf samtools-1.19.2.tar.bz2
cd samtools-1.19.2/
cd htslib-1.19.1/
./configure
```
を行うと
”
configure: error: libbzip2 development files not found

The CRAM format may use bzip2 compression, which is implemented in HTSlib
by using compression routines from libbzip2 <http://www.bzip.org/>.

Building HTSlib requires libbzip2 development files to be installed on the
build machine; you may need to ensure a package such as libbz2-dev (on Debian
or Ubuntu Linux) or bzip2-devel (on RPM-based Linux distributions or Cygwin)
is installed.
”
とメッセージが出ています。この場合、どのようにすればよろしいでしょうか？

**Comment by oogasawa** [comment]
Github discusionsの方に移しました。
https://github.com/nig-sc/nigsc_homepage2/discussions/450
